### ISSUE TITLE
Not really an issue but a question and a request

### ISSUE THREAD

**Issue by jumping2000** [diyruz/flower#1]
Hi,
just two questions;

1. does the "flower" firmware work only with bme280 sensor?
2 I read here https://modkam.ru/?p=1671 that the measurement and transmission interval is 1 minute, is it possbile to change to 15 minute? 

thank you for the great work

**Comment by nurikk** [comment]
Hi, reporting interval is 30 minutes. It only supports bme280 and ds1820 sensors

**Comment by jumping2000** [comment]
Perfect! thank you!
