### ISSUE TITLE
Light sensor

### ISSUE THREAD

**Issue by madman2143** [diyruz/flower#30]
Thank you for this great project.

What sensor is utilized for light level sensing by design? There are several parts available to order, which one is recommended?

**Comment by bojanpotocnik** [comment]
@madman2143 

> which one is recommended?

Probably the one used in the project - on schematics [v1](https://modkam.ru/?p=1671), [v2](https://modkam.ru/?p=1700) and [v3](https://modkam.ru/?p=1832) there is [3528-PTSM D3528](https://lcsc.com/product-detail/Ambient-Light-Sensors_Shenzhen-Jing-Chuang-He-Li-Tech-3528-PTSM-D3528_C242256.html). Or some [alternatives](https://github.com/diyruz/flower/issues/19#issuecomment-864598560) mentioned in #19.

_Please close the issue if this answered your question._

**Comment by madman2143** [comment]
Thank you!
