### ISSUE TITLE
custom sensor

### ISSUE THREAD

**Issue by jumping2000** [diyruz/flower#5]
I built a custom and very compact version of  your "flower" sensor  with only BME280 sensor and It seems to work!
the only problem is with the attribute exposed to Home Assistant, I have some attribute with "_1", maybe there is something strange in the "converter file"? 

battery: 100
humidity: 88.42
illuminance: 2959
illuminance_1: 2954
illuminance_lux: 2
illuminance_lux_1: 2
linkquality: 33
pressure: 964.7
soil_moisture: 100
temperature_1: 21.21
temperature_bme: 22.6
voltage: 3500
unit_of_measurement: °C
friendly_name: 0x00124b001bdd56d3_temperature
device_class: temperature

thank you

**Comment by jumping2000** [comment]
I use 2.03 firmware and related "conveerter file"

**Comment by nurikk** [comment]
z2m natively supports this sensor, no external converter required

**Comment by jumping2000** [comment]
> z2m natively supports this sensor, no external converter required

I removed the converter from z2m configuration but I have some strange data ending with "_1", is it normal?

{
    "battery": 52,
    "humidity": 64.48,
    "humidity_1": 47.71,
    "illuminance": 1911,
    "illuminance_1": 2615,
    "illuminance_lux": 2,
    "illuminance_lux_1": 2,
    "linkquality": 36,
    "pressure": 979.3,
    "pressure_1": 965,
    "soil_moisture": 100,
    "temperature_1": 26.61,
    "temperature_bme": 19.7,
    "voltage": 2900
}

**Comment by jumping2000** [comment]
solved after 2-3 re-pairing end new version of zigbee2mqtt, Now I have the correct sensor!
